###
GET http://10.22.22.97:3090/api/get_data_info?dataId=769 HTTP/1.1

###
POST http://10.22.22.97:3090/api/path_analysis HTTP/1.1
content-type: application/json

{
    "dataId": "769",
    "target": "信用卡交易金額[新台幣]",
    "concept_hierarchy": {
        "教育程度類別": {
            "hierarchy": {"高中以下": ["高中高職", "其他"], "大專": ["專科", "大學"], "研究所": ["碩士", "博士"]},
            "order": ["高中以下", "大專", "研究所"]
        }
    }
}

###
POST http://10.22.22.97:3090/api/process_pivot_analysis HTTP/1.1
content-type: application/json

{
    "dataId": "769",
    "target": "信用卡交易金額[新台幣]",
    "process": [["信用卡交易筆數", ["middle", "high"]], ["信用卡交易筆數", ["high"]], ["地區", ["臺北市"]], ["教育程度類別", ["研究所"]], ["產業別", ["食", "衣", "住", "行"]], ["產業別", ["食", "衣"]]]
}